# Generated by Django 4.0.2 on 2022-04-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_alter_image_height_alter_image_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='codec',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='orig_format',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='orig_mode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='ratio',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
