# Generated by Django 4.0.2 on 2022-05-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0004_group_alter_image_options_imageingroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
