# Generated by Django 4.0.2 on 2022-05-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0007_alter_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.CharField(blank=True, default='ggYySYCm', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
