# Generated by Django 4.0.2 on 2022-05-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0009_alter_group_slug_alter_image_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, null=True),
        ),
    ]
