# Generated by Django 4.0.2 on 2022-05-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0010_alter_group_slug_alter_image_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('uploaded',)},
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
