# Generated by Django 4.0.2 on 2022-05-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0011_alter_image_options_alter_group_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageingroup',
            options={'ordering': ('image__uploaded',)},
        ),
    ]
